- src/styles/bootstrap.less
- src/styles/colors.less
- src/styles/variables.less
Generated color variables as defined on the helix-docs-site and included our starting variables into the properly documented variables.less file for easier refactoring in the future.
> Add helix variables

- source/_data/nav.yml
- source/_less/vars.less
- source/components/text-input/index.html
- source/components/text-input/text-input.less
- source/helix-ui.less
JIRA: https://jira.rax.io/browse/SURF-512
> feat(input): Build Text Input Styles

- source/_less/scaffold.less
- source/_templates/partials/after_footer.njk
- source/_templates/partials/head.njk
- source/components/grid/index.html
- source/components/icon/index.html
- source/components/navigation/index.html
- source/components/table/table.less
- source/components/typography/typography.less
- source/guides/install/index.html
JIRA: 
* https://jira.rax.io/browse/SURF-735
* https://jira.rax.io/browse/SURF-623 (partial)
> Remove bs dependency

- source/_data/nav.yml
- source/components/status-label/index.html
- source/components/status-label/status-label.less
- source/helix-ui.less
JIRA: https://jira.rax.io/browse/SURF-684
> feat(status label): Build Status Label

- bin/start.js
> fix(server): Avoid mass file change events

- .eslintrc.json
- source/components/checkbox/HxCheckbox.js
- source/components/icon/HxIcon.js
- source/components/reveal/HxReveal.js
- source/components/tabset/HxTabpanel.js
- source/components/tabset/HxTabset.js
Update ESLint config to catch stuff it previously missed.
> fix(eslint): modify eslint config to catch missing stuff

- LICENSE
- package.json
Updating package metadata to prepare for work needed to publish assets to NPM.
> update(package): update metadata and add license

- source/_data/nav.yml
- source/components/disclosure/HxDisclosure.js
- source/components/disclosure/disclosure.less
- source/components/disclosure/index.html
- source/components/reveal/HxReveal.js
- source/helix-ui.js
- source/helix-ui.less
JIRA: https://jira.rax.io/browse/SURF-745
> surf-745-disclosure

- .eslintrc.json
- source/_data/nav.yml
- source/_templates/partials/after_footer.njk
- source/components/box/box-demo.js
- source/components/box/box-docs.less
- source/components/box/box.less
- source/components/box/index.html
- source/components/panel/index.html
- source/components/panel/panel-demo.js
- source/components/panel/panel-docs.less
- source/components/panel/panel.less
- source/docs.js
- source/docs.less
- source/helix-ui.less
JIRA: https://jira.rax.io/browse/SURF-746
* Added Panel component
* Added Box component
> feat(components): add Panel and Box

- source/lib/position/index.js
- source/lib/position/offsetFunctions.js
Position library necessary for other PRs.
```javascript
import { getPosition } from 'lib/position';
let pos = getPosition(targetElement, referenceElement, position); 
// pos => { x: <Integer>, y: <Integer>, position: <String> }
```
> feat(position): add position lib

- .eslintrc.json
- source/lib/position/index.js
- source/lib/position/offsetFunctions.js
JIRA: N/A -- additions were added into the positing library so that alignment works (pointed out in Action Menu story) and so that the arrow is an optional parameter
> refactor(position): additional positioning

- docs/_data/nav.json5
- docs/components/component-status/index.html
- source/_data/nav.yml
- source/components/component-status/index.html
- src/helix-ui/styles/core/hx-status.less
> chore(wip): helix-ui compatibility table

- rollup.config.js
- src/helix-ui/index.js
Fix bug introduced in hack-a-thon from IA reorg
> fix(polyfill): fix race condition

- docs/elements/hx-disclosure/index.html
- docs/elements/hx-reveal/index.html
JIRA: https://jira.rax.io/browse/SURF-751
> surf-751-reveal-fix

- docs/_data/nav.json5
- docs/components/menus/index.html
> fix(nav): add Menus back to nav

- test/bin/util.ts
- test/bin/visreg.example.config.ts
- test/bin/visreg.ts
- test/types/inquirer-shortcuts.d.ts
JIRA: https://jira.rax.io/browse/SURF-737
I fixed this weeks ago and forgot to push it up and make a pull request!
> fix(visreg): Ask for github username, not sso

- docs/docs.less
- docs/index.html
JIRA: https://jira.rax.io/browse/SURF-813
> surf-813-helixui-homepage

- package.json
> chore(release): v0.2.1 [skip ci]

- src/helix-ui/elements.js
- src/helix-ui/elements/HXMenuElement.js
- src/helix-ui/elements/HXMenuitemElement.js
JIRA: https://jira.rax.io/browse/SURF-811
> fix(menus): correct ARIA attributes

- src/helix-ui/elements/_hx-checkbox.less
- src/helix-ui/elements/_hx-modal.less
- src/helix-ui/elements/_hx-popover.less
- src/helix-ui/elements/_hx-tooltip.less
JIRA: https://jira.rax.io/browse/SURF-840
Paragraph should have a box-sizing of `border-box`.
Paragraph has a box-sizing of `border-box`.
> fix(css): correct ShadowDOM CSS

- docs/components/box/index.html
- docs/components/menus/index.html
- src/helix-ui/styles/modules/button.less
JIRA: https://jira.rax.io/browse/SURF-775
> feat(button): Cog Button

- package.json
> chore(release): v0.3.0 [skip ci]

- docs/_util.js
- test/scripts/webdriver-update
Utility to help with generating HTML snippets in the VueJS demo javascript.
> docs(util): add util JS for code snippets

- docs/_data/nav.json5
- docs/components/busy/busy-demo.js
- docs/components/busy/index.html
- docs/docs.js
- docs/elements/hx-busy/index.html
- docs/elements/hx-checkbox/index.html
- src/helix-ui.less
- src/helix-ui/elements.js
- src/helix-ui/elements/HXBusyElement.js
- src/helix-ui/styles/core/hx-busy.less
- src/helix-ui/styles/modules/button.less
JIRA: https://jira.rax.io/browse/SURF-399
> feat(busy): add Busy component

- docs/components/choice-tiles/test.html
> docs(choiceTiles): tile grid example

- src/helix-ui/styles/modules/text-input.less
> fix(TextInputs): correct textarea padding

- src/helix-ui/styles/modules/stepper.less
Fix issue : https://github.com/rackerlabs/helix-ui/issues/167
> fix: corrected stepper header style to apply only for accordion header.  Fix #167

- package.json
> chore(release): v0.4.2 [skip ci]

- docs/_data/nav.json5
- docs/components/pagination/index.html
- src/helix-ui.less
- src/helix-ui/styles/modules/pagination.less
JIRA:  https://jira.rax.io/browse/SURF-676
> feat(pagination): pagination styles added to toolkit

- src/helix-ui/styles/alert.less
- src/helix-ui/styles/reset.less
JIRA: https://jira.rax.io/browse/SURF-953
> fix(CSS): correct alert dismiss styling

- package.json
> chore(release): v0.5.0 [skip ci]

- src/helix-ui/elements/_hx-modal.less
- src/helix-ui/styles/core/hx-modal.less
- src/helix-ui/styles/modules/stepper.less
Closes #183
Closes #184
Closes #185
Component | Before | After
----- | ----- | -----
Modal | ![screen shot 2018-04-02 at 5 38 12 pm](https://user-images.githubusercontent.com/545605/38219844-347f6f74-369d-11e8-8470-977608c67d52.png) | ![screen shot 2018-04-02 at 5 38 19 pm](https://user-images.githubusercontent.com/545605/38219849-3b056a6a-369d-11e8-8fe0-dc9e1fdef6ab.png)
Stepper | ![screen shot 2018-04-02 at 5 38 47 pm](https://user-images.githubusercontent.com/545605/38219855-41b906fa-369d-11e8-837b-20b3e8eba5d5.png) | ![screen shot 2018-04-02 at 5 38 32 pm](https://user-images.githubusercontent.com/545605/38219857-46289502-369d-11e8-826b-55c815675945.png)
> fix(CSS): correct multiple CSS issues w/ ShadyDOM

- package.json
> chore(release): v0.5.2 [skip ci]

- docs/_data/nav.json5
- docs/components/alerts/alert-demo.js
- docs/components/alerts/index.html
- docs/docs.js
- docs/elements/hx-alert/index.html
- src/helix-ui.less
- src/helix-ui/elements.js
- src/helix-ui/elements/HXAlertElement.js
- src/helix-ui/elements/HXElement.js
- src/helix-ui/elements/_hx-alert.html
- src/helix-ui/elements/_hx-alert.less
- src/helix-ui/styles/components/alerts.less
- src/helix-ui/styles/core/hx-alert.less
JIRA: [SURF-675](https://jira.rax.io/browse/SURF-675)
> feat(alert): add alert component

- package.json
> chore(release): v0.6.0 [skip ci]

- docs/components/icons/icon-demo.js
Fix url for rackerlabs.github.io
> docs(Icons): fix ajax call

- package.json
> chore(release): v0.6.1 [skip ci]

- src/COMPATIBILITY.md
Findings around polyfills required to remove polyfill.io as a 3rd party dependency.
JIRA: https://jira.rax.io/browse/SURF-1048
> docs(compat): Add COMPATIBILITY.md

- src/helix-ui.less
- src/helix-ui/styles/helpers.less
- src/helix-ui/styles/modules/grid.less
updates based on feedback from CTUI
> refactor(*): feedback from CTUI

- package.json
- yarn.lock
> fix(package): add jsdoc [skip ci]

- docs/_templates/partials/footer_nav.njk
- docs/index.html
- src/helix-ui/styles/components/layouts.less
> docs(layout): Add GitHub links

- .travis.yml
> chore(travis): Stop sending emails

- docs/components/search/index.html
- docs/elements/hx-search-assistance/index.html
> docs(minver): update minver for hx-search-assistance

- docs/docs.less
- src/helix-ui/styles/components/breadcrumbs.less
- src/helix-ui/styles/elements/hx-disclosure.less
- src/helix-ui/styles/elements/hx-icon.less
- src/helix-ui/styles/elements/hx-tile.less
JIRA: https://jira.rax.io/browse/SURF-1076
Closes #207 
Item | Before | After
----- | ----- | -----
Alert "X" | ![alert-before](https://user-images.githubusercontent.com/545605/39332733-f5ec1738-496d-11e8-9f67-eaaaed0ecae4.png) | ![alert-after](https://user-images.githubusercontent.com/545605/39332734-f5fc89b0-496d-11e8-86ac-175141ae1e87.png)
Breadcrumb Delimiters | ![breadcrumb-before](https://user-images.githubusercontent.com/545605/39332671-c2a1528a-496d-11e8-8672-9c6ce666b016.png) | ![breadcrumb-after](https://user-images.githubusercontent.com/545605/39332670-c293a400-496d-11e8-8eee-8c455356ecbe.png)
Icon (Konami Code) | ![icon-demo-before](https://user-images.githubusercontent.com/545605/39334276-a09f5b5e-4973-11e8-9fd6-ce867ae22c7f.png) | …
> fix(hx-icon): correct alignment of <hx-icon>

- docs/elements/hx-accordion-panel/index.html
- docs/elements/hx-accordion/index.html
- docs/elements/hx-alert/index.html
- docs/elements/hx-busy/index.html
- docs/elements/hx-checkbox/index.html
- docs/elements/hx-disclosure/index.html
- docs/elements/hx-menu/index.html
- docs/elements/hx-modal/index.html
- docs/elements/hx-popover/index.html
- docs/elements/hx-reveal/index.html
- docs/elements/hx-search-assistance/index.html
- docs/elements/hx-search/index.html
- docs/elements/hx-tooltip/index.html
JIRA: free friday cleanup
*** making element documentation in sync
> refactor(element-docs): make elements documentations in sync

- package.json
> chore(release): 0.8.0 [skip ci]

- docs/_data/nav.json5
- docs/components/icons/index.html
- docs/elements/hx-file-icon/index.html
- src/helix-ui/elements.js
- src/helix-ui/elements/HXFileIconElement.html
- src/helix-ui/elements/HXFileIconElement.js
- src/helix-ui/elements/HXFileIconElement.less
- src/helix-ui/styles/elements.less
- src/helix-ui/styles/elements/hx-file-icon.less
> feat(hx-file-icon): new element styles added for hx-file-icon

- src/helix-ui/styles/components/buttons.less
Per feedback from dashboard meeting. Corrects the display if the `.hxBtn` class is applied to an inline element.
> fix(Buttons): correct button display CSS

- docs/components/lists/index.html
- src/helix-ui/styles/base/lists.less
JIRA: Surf-706
Ordered and Unordered Lists
> feat(lists): styles for ordered and unordered lists

- docs/_data/nav.json5
- docs/components/badges/index.html
- src/helix-ui/styles/components.less
- src/helix-ui/styles/components/badges.less
- src/helix-ui/styles/elements/hx-tab.less
> feat(Badge): add badge component

- docs/components/modals/index.html
- test/common/util.ts
- test/tsconfig.json
- test/visreg/visreg.ts
> test(Modal): add visual regression tests

- docs/elements/hx-tooltip/index.html
JIRA: no JIRA, just noticed a typo
> Add the missing greater-than

- docs/_data/cdn.json5
- docs/_templates/guide.njk
- docs/_templates/partials/after_footer.njk
- docs/_templates/partials/head.njk
- docs/components/icons/icon-demo.js
- docs/components/icons/index.html
- docs/components/layouts/horizontal-layout-template.html
- docs/components/layouts/vertical-layout-template.html
- docs/docs.less
- docs/guides/getting-started/index.html
- lib/generate.js
- package.json
- src/helix-ui/styles/base/lists.less
- src/helix-ui/styles/components.less
- src/helix-ui/styles/components/buttons.less
- src/helix-ui/styles/components/panels.less
- src/helix-ui/styles/components/tabs.less
- yarn.lock
JIRA: SURF-1147, SURF-879 (partially)
> docs(downloads): modify getting started guide

- docs/components/badges/index.html
- docs/components/icons/index.html
- docs/components/lists/index.html
- docs/components/pills/index.html
- docs/components/progress/index.html
- docs/components/selector-strips/index.html
- docs/components/toasts/index.html
- docs/elements/hx-file-icon/index.html
- docs/elements/hx-pill/index.html
- docs/elements/hx-progress/index.html
- docs/elements/hx-toast/index.html
> docs(minver): update minimum versions

- docs/guides/getting-started/index.html
> docs(download): add 3rd party dependency disclaimer

- docs/components/text-inputs/index.html
- test/common/util.ts
- test/visreg/visreg.ts
> Vis reg test suites for Text input component.

- docs/_data/nav.json5
- docs/components/file-tiles/file-tile-demo.js
- docs/components/file-tiles/index.html
- docs/components/icons/index.html
- docs/docs.js
- docs/docs.less
- docs/elements/hx-file-icon/index.html
- docs/elements/hx-file-tile/index.html
- src/helix-ui/elements.js
- src/helix-ui/elements/HXFileIconElement.less
- src/helix-ui/elements/HXFileTileElement.html
- src/helix-ui/elements/HXFileTileElement.js
- src/helix-ui/elements/HXFileTileElement.less
- src/helix-ui/styles/elements.less
- src/helix-ui/styles/elements/hx-file-tile.less
> feat(file-upload-tile): styles added for new component

- .eslintrc.json
- .eslintrc.prod.json
- .travis.yml
- package.json
- allow js compliation if linting errors present (with warnings)
- fail CI/CD if linting errors present
- fix linting issues in polyfill
JIRA: Free Friday
> chore(linting): reconfigure eslint

- docs/_templates/partials/after_footer.njk
- docs/components/icons/icon-demo.js
- docs/docs.js
- package.json
- yarn.lock
- replace `$.ajax()` with `fetch()`
JIRA: Free Friday
> docs(refactor): remove jquery

- docs/_data/nav.json5
JIRA: *** no jira, commenting file tiles out of the nav until design and dev align for file tiles ***
> docs(nav): remove file tile

- docs/_data/nav.json5
- docs/components/typography/index.html
- docs/elements/hx-error/index.html
added missing documentation for hx-error custom element
> docs(hx-error): add documentation for custom element

- docs/components/search/test.html
- docs/elements/hx-accordion/index.html
- docs/elements/hx-alert/index.html
- docs/elements/hx-checkbox/index.html
- docs/elements/hx-disclosure/index.html
- docs/elements/hx-file-tile/index.html
- docs/elements/hx-pill/index.html
- docs/elements/hx-search/index.html
- docs/elements/hx-tabset/index.html
- docs/elements/hx-toast/index.html
- src/helix-ui/elements/HXAccordionElement.js
- src/helix-ui/elements/HXAlertElement.js
- src/helix-ui/elements/HXCheckboxElement.js
- src/helix-ui/elements/HXDisclosureElement.js
- src/helix-ui/elements/HXElement.js
- src/helix-ui/elements/HXFileTileElement.js
- src/helix-ui/elements/HXPillElement.js
- src/helix-ui/elements/HXSearchElement.js
- src/helix-ui/elements/HXTabsetElement.js
- src/helix-ui/elements/HXToastElement.js
- src/helix-ui/elements/HXTooltipElement.js
JIRA: n/a
Add declarative functionality to aid in testing and improve usage flexibility.
> Add declarative functionality

- package.json
> Release 0.11.0

- netlify.toml
Enables Netlify deploy previews (see checks for this PR).
> Setup Netlify Deploy Previews

- docs/components/buttons/index.html
JIRA: n/a
Preview: https://deploy-preview-291--helix-ui.netlify.com/
> docs(Buttons): do not promote non-interactive anchor buttons

- package.json
* Add `yarn install:clean` script
Also testing updated Netlify notification settings.
> chore(yarn): add install:clean script

- docs/elements/hx-busy/index.html
- docs/elements/hx-progress/index.html
- docs/elements/hx-status/index.html
> docs(elements): fix cross-links to Component docs

- docs/components/layouts/horizontal-layout-template.html
- docs/components/layouts/vertical-layout-template.html
Polyfills were removed in #270, so removing them from the templates.
> Removing polyfills from layout templates

- docs/_data/nav.json5
- docs/components/files/file-input-demo.js
- docs/components/files/index.html
- docs/components/files/test-file-selectors.html
- docs/components/files/test-file-tiles.html
- docs/docs.js
- docs/elements/hx-file-input/index.html
- src/helix-ui/elements.js
- src/helix-ui/elements/HXFileInputElement.html
- src/helix-ui/elements/HXFileInputElement.js
- src/helix-ui/elements/HXFileInputElement.less
- src/helix-ui/styles/elements.less
- src/helix-ui/styles/elements/hx-file-input.less
> new(feat): file input styles

- docs/components/popovers/test.html
- docs/components/tooltips/test.html
- package.json
- src/helix-ui/elements/HXPopoverElement.js
- src/helix-ui/elements/HXTooltipElement.js
Fixes #303 for v0.13.0. Reviewed in #304.
> [v0.13.0] Fix Issue 303

- docs/components/files/file-input-demo.js
- docs/components/files/file-tile-demo.js
- docs/components/files/index.html
- docs/components/icons/icon-demo.js
- docs/components/icons/index.html
> docs(*): limit available icons in demos

- test/behavioral/behavioral.ts
- test/behavioral/tests/tabs.ts
- test/common/util.ts
JIRA: SURF-1189
Removal of XPath and optimization of current test suites.
> Unit testing in helix

- src/helix-ui/elements/HXFileTileElement.less
> chore(file-tile): add focus styles

- docs/styles/demo/box-docs.less
- src/helix-ui/elements/index.js
- Fix CSS for `div.hxBox` demo
- Add HXDivElement back to list of all elements
> fix(Box): correct bugs with Box

- package.json
> chore(release): v0.13.1 [skip ci]

- src/polyfills/Element.js
> fix(polyfills): correct typo in polyfill

- src/helix-ui/styles/elements/hx-tabcontent.less
> fix(tabs): correct flex-basis

- docs/guides/getting-started/index.html
- src/helix-ui/styles/elements/hx-tabcontent.less
JIRA: n/a (RAX.io preparation)
> Docs raxio 2018

- src/helix-ui/styles/elements/hx-tabcontent.less
- src/helix-ui/styles/elements/hx-tablist.less
- src/helix-ui/styles/elements/hx-tabpanel.less
- src/helix-ui/styles/elements/hx-tabset.less
* convert Tabs component layout from Flexbox to CSS grid
JIRA: n/a
> fix(Tabs): correct tabs layout

- docs/_data/nav.json5
- docs/components/files/index.html
- docs/components/files/test-drop-fences.html
- docs/components/files/test-drop-zones.html
- docs/elements/hx-drop-fence/index.html
- src/helix-ui/elements/HXDropFenceElement.html
- src/helix-ui/elements/HXDropFenceElement.js
- src/helix-ui/elements/HXDropFenceElement.less
- src/helix-ui/elements/index.js
- src/helix-ui/styles/elements.less
- src/helix-ui/styles/elements/hx-drop-fence.less
- src/helix-ui/styles/elements/hx-drop-zone.less
> surf-1383-hx-fence

- src/helix-ui/styles/reset/forms.less
JIRA:  merged into css audit branch
> chore(wip): audit css

- src/helix-ui/elements/HXFileTileElement.js
> new(feat): tooltip on truncated links for file tiles

- docs/components/files/file-tile-demo.js
- docs/components/files/index.html
- docs/components/files/test-file-tiles.html
- docs/elements/hx-file-tile/index.html
- src/helix-ui/elements/HXAlertElement.js
- src/helix-ui/elements/HXFileTileElement.js
- src/helix-ui/elements/HXFileTileElement.less
Update `<hx-file-tile>` to have a `readonly` attribute.
**JIRA: SURF-1341**
> feat(hx-file-tile): surf-1341 readonly file tile

- src/helix-ui/styles/components/text-inputs.less
> fix(text-input): correct disabled placeholder styles, all browsers

- docs/components/loaders/index.html
> fix(loader-button): wrapped word in span to fix broken styles

- package.json
Bump version after NPM release
> Release 0.14.0

- src/helix-ui/styles/components/choice-tiles.less
- src/helix-ui/styles/components/navigation.less
- src/helix-ui/styles/elements/hx-tab.less
> fix(choice-tiles): cursor pointer style added to hover

- src/helix-ui/styles/components/choice-tiles.less
> fix(choice-tiles): icon color when selected styles added

- .editorconfig
> chore(pipeline): add .editorconfig

- README.md
Hi, just added some details for the readme. Please feel free to change, etc. Thanks!
Links to the docs, etc.
JIRA:
> Update for readme

- src/helix-ui/index.js
- src/helix-ui/index.spec.js
> chore(wip): initialize functionality for careathon

- .npmrc
* change pre-release version format from `vX.Y.Z-N` to `vX.Y.Z-rc.N`
* configure commit message format applied by `npm version` (see screenshot)
> chore(npmrc): tweak npm config

- test/scripts/run-travis-push-or-pr
> chore(saucelabs): disable saucelabs testing, for now

- package.json
> chore(release): v0.15.0-rc.0 [skip ci]

- docs/components/pills/index.html
- docs/components/pills/test.html
- src/helix-ui/styles/elements/hx-pill.less
> fix(pills): fix styles for pills inside tables

- docs/elements/hx-accordion-panel/index.html
- docs/elements/hx-accordion/index.html
- docs/elements/hx-busy/index.html
- docs/elements/hx-checkbox/index.html
- docs/elements/hx-disclosure/index.html
- docs/elements/hx-drop-zone/index.html
- docs/elements/hx-file-icon/index.html
- docs/elements/hx-file-input/index.html
- docs/elements/hx-file-tile/index.html
- docs/elements/hx-menu/index.html
- docs/elements/hx-menuitem/index.html
- docs/elements/hx-modal/index.html
- docs/elements/hx-panel/index.html
- docs/elements/hx-panelbody/index.html
- docs/elements/hx-panelfoot/index.html
- docs/elements/hx-panelhead/index.html
- docs/elements/hx-pill/index.html
- docs/elements/hx-popover/index.html
- docs/elements/hx-reveal/index.html
- docs/elements/hx-search-assistance/index.html
- docs/elements/hx-search/index.html
- docs/elements/hx-tabcontent/index.html
- docs/elements/hx-tile/index.html
- docs/elements/hx-toast/index.html
- docs/elements/hx-tooltip/index.html
> feat(normalize-docs): normalize custom elements documentation

- docs/components/pills/index.html
- docs/components/pills/pill-demo.js
- docs/components/pills/test.html
- docs/elements/hx-pill/index.html
- src/helix-ui/elements/HXPillElement.js
- src/helix-ui/elements/HXPillElement.less
> fix(hx-pill): invert dismissible behaviour with persist

- src/helix-ui/styles/components/tables.less
* remove bottom margin from `<table>` if it's the last child of a container
JIRA: SURF-1282
> fix(table): surf-1282 tables no sibs no bottom margin

- docs/_templates/lorem.njk
- docs/components/modals/index.html
- docs/components/modals/test.html
- docs/components/popovers/index.html
- package.json
- src/helix-ui/elements/HXDivElement.html
- src/helix-ui/elements/HXDivElement.js
- src/helix-ui/elements/HXDivElement.less
- src/helix-ui/styles/components/box.less
- src/helix-ui/styles/elements/hx-div.less
- src/helix-ui/styles/elements/hx-modal.less
- src/helix-ui/styles/elements/hx-popover.less
- src/helix-ui/styles/vars.less
- yarn.lock
Avoid padding-block-end bug with scrolling hx-div
by moving padding to a shadow/shady child element.
Closes: #379
> fix(hx-div): fix padding-block-end bug

- docs/components/files/index.html
> docs(Files): correct broken "see also" link

- docs/components/alerts/alert-demo.js
- docs/components/alerts/index.html
- docs/components/toasts/index.html
- docs/components/toasts/toast-demo.js
- docs/elements/hx-alert/index.html
- src/helix-ui/elements/HXAlertElement.js
- src/helix-ui/elements/HXAlertElement.less
> fix(hx-alert): exchange static attr  with persist

- docs/elements/hx-accordion/index.html
- docs/elements/hx-drop-zone/index.html
- docs/elements/hx-file-tile/index.html
- docs/elements/hx-menu/index.html
- docs/elements/hx-popover/index.html
- docs/elements/hx-search-assistance/index.html
- docs/elements/hx-tooltip/index.html
> docs(pills): update pills with recent persist update

- docs/components/accordions/index.html
- docs/components/accordions/test.html
- docs/elements/hx-accordion-panel/index.html
- src/helix-ui/elements/HXAccordionPanelElement.js
- src/helix-ui/elements/HXAccordionPanelElement.less
> feat(disabled): add disabled attr to accordion-panel

- package.json
> chore(release): v0.15.0-rc.1 [skip ci]

- docs/elements/hx-search-assistance/index.html
- src/helix-ui/elements/HXSearchAssistanceElement.js
* Refactored `HXSearchAssistance` to use the `Positionable` mixin.
JIRA: SURF-1498
> refactor(hx-search-assistance): surf-1498 use positionable mixin

- src/helix-ui/elements/HXAccordionElement.js
- src/helix-ui/elements/HXDisclosureElement.js
- src/helix-ui/elements/HXElement.js
- src/helix-ui/elements/HXTabsetElement.js
- src/helix-ui/elements/HXTooltipElement.js
- src/helix-ui/utils/index.js
* Accordion
* use new `replaceWith` util
* Disclosure
* defer `$onConnect` to give target a chance to initialize
* add private methods to abstract target event listener subscriptions
* fix `target` getter logic to be aware if connected
* Tabset
* defer `$onConnect` to let children initialize before parent
* refactor to use new util methods
* Tooltip
* refactor to use new `generateId` util method
JIRA: SURF-1515
> [412] refactor(HXElement): refactor behavior of multiple custom elements

- src/helix-ui/mixins/Positionable.js
* refactor `Positionable` mixin based on `Compatibility Audit`
JIRA: SURF-1518
> [412] refactor(mixin): compatability audit updates to positionable mixin

- src/helix-ui/elements/HXTooltipElement.js
> surf-1517-tooltip-compat-audit

- docs/_data/polyfilled-apis.json5
- src/polyfills/Node.js
- src/polyfills/index.js
* update Polyfills guide
* add `Node.prototype.isConnected` polyfill
JIRA: n/a
> feat(polyfills): add Node.prototype.isConnected polyfill

- src/helix-ui/elements/HXDivElement.js
* refactor `HXDiv` based on `Compatibility Audit`
JIRA: SURF-1516
> refactor(hx-div): compatability audit updates

- src/helix-ui/elements/HXTabsetElement.js
> [412] Update HXTabsetElement.js

- src/helix-ui/elements/HXAccordionElement.js
- src/helix-ui/elements/HXDisclosureElement.js
- src/helix-ui/elements/HXDivElement.js
- src/helix-ui/elements/HXDropFenceElement.js
- src/helix-ui/elements/HXErrorElement.js
- src/helix-ui/elements/HXFileIconElement.js
- src/helix-ui/elements/HXIconElement.js
- src/helix-ui/elements/HXModalElement.js
- src/helix-ui/elements/HXPopoverElement.js
- src/helix-ui/elements/HXSearchElement.js
- src/helix-ui/elements/HXTabpanelElement.js
- src/helix-ui/elements/HXTabsetElement.js
- src/helix-ui/elements/HXTooltipElement.js
JIRA: no jira, as i was comparing javascript element files, noticed inconsistencies with the imports at the top of the file so quick fix to make them consistent
> free-friday-organize-js

- docs/components/tooltips/test.html
- src/helix-ui/mixins/Positionable.js
> Debug tooltip compat audit

- src/helix-ui/elements/HXAccordionElement.js
> surf-1514-accordion-compatibility-audit

- src/helix-ui/elements/HXTabsetElement.js
* refactor `HXTabsetElement` with compatibility audit fixes
JIRA: SURF-1500
> [412] refactor(tabset): surf-1500 apply compatibility audit fixes for tabs

- docs/_templates/partials/app_nav.njk
> [412] fix(docs): fix invalid HTML id in nav

- src/helix-ui/styles/helpers/alignment.less
* Add utility alignment classes to tables
* Fixes Issue #394 
JIRA: SURF-1546
> [issue 394] chore(tables): surf-1546 table css resets

- package.json
> chore(release): v0.15.0 [skip ci]

- docs/components/typography/index.html
- docs/components/typography/test.html
> fix(hx-error): fix error message to error text

- docs/components/tooltips/index.html
> dox(tooltips): fix typo in code snippet

- lib/compile.js
- lib/generate.js
> chore(pipeline): add LESS error feedback

- docs/_data/nav.json5
- docs/_templates/application.njk
- docs/_templates/partials/head.njk
- docs/_templates/test.njk
- docs/components/dropdown-select/index.html
- docs/components/dropdown-select/select-demo.js
- docs/components/dropdown-select/test.html
- docs/docs.js
- docs/docs.less
- docs/scripts/test-helpers.js
- docs/styles/demo/dropdown-select-docs.less
- docs/styles/docs-test.less
- src/helix-ui/elements/HXSelectElement.html
- src/helix-ui/elements/HXSelectElement.js
- src/helix-ui/elements/HXSelectElement.less
- src/helix-ui/elements/index.js
- src/helix-ui/styles/components.less
- src/helix-ui/styles/components/dropdown-select.less
- src/helix-ui/styles/config.less
- src/helix-ui/styles/mixins.less
- src/helix-ui/styles/mixins/microsoft.less
- src/helix-ui/styles/mixins/mozilla.less
- src/helix-ui/styles/mixins/standard.less
- src/helix-ui/styles/mixins/webkit.less
- src/helix-ui/styles/vars.less
> feat(DropdownSelect): Add Select component

- src/helix-ui/elements/HXElement.js
> feat(HXElement): add 'hx-defined' attr on connect

- docs/_templates/component.njk
- docs/_templates/element.njk
- docs/_templates/guide.njk
- docs/_templates/partials/sidebar.njk
- docs/_templates/test.njk
- docs/components/accordions/test.html
- docs/docs.less
> docs(*): refactor docs layouts

- src/helix-ui/elements/HXFileTileElement.less
- src/helix-ui/elements/HXToastElement.less
- src/helix-ui/styles/components.less
- src/helix-ui/styles/components/loaders.less
- src/helix-ui/styles/components/menus.less
- src/helix-ui/styles/components/progress.less
- src/helix-ui/styles/components/search.less
JIRA: fast-follow to https://github.com/rackerlabs/helix-ui/pull/471
> refactor(fast-follow): css into components less fixes

- docs/components/radios/index.html
- docs/components/radios/radio-demo.js
- docs/components/radios/test.html
- docs/docs.js
- docs/docs.less
- docs/styles/demo/radios-docs.less
- src/helix-ui/styles/components.less
- src/helix-ui/styles/components/radios.less
* `Radio` (`<hx-radio-control>`) Phase I 
```html
<hx-radio-control>
<input type="radio" id="rad1" />
<label for="rad1">
<hx-radio></hx-radio>
Radio Button 1
</label>
</hx-radio-control>
```
> [^459] feat(hx-radio-control): surf-584 phase I radio form control

- package.json
> chore(release): v0.16.0-rc.0 [skip ci]

- docs/components/checkboxes/test.html
- docs/styles/demo/checkbox-docs.less
- src/helix-ui/styles/components/checkbox.less
> surf-1593-checkbox-phase-2

- package.json
> chore(release): v0.16.0-rc.1 [skip ci]

- docs/components/dropdown-select/test.html
- docs/components/text-input/test.html
- docs/components/textarea/test.html
- src/helix-ui/styles/components/text-input.less
- src/helix-ui/styles/components/textarea.less
> refactor(TextControls): phase 2.5 CSS refactoring

- docs/components/radios/index.html
- docs/components/radios/radio-demo.js
- docs/components/radios/test.html
- docs/docs.less
- docs/styles/spec/radio-spec.less
- src/helix-ui/elements/HXFormControlElement.js
- src/helix-ui/elements/HXRadioSetElement.js
- src/helix-ui/elements/index.js
- src/helix-ui/styles/components/radios.less
> chore(wip): surf-1595 radio phase 2 + phase 2.5

- package.json
> chore(release): v0.16.0-rc.2 [skip ci]

- docs/components/menus/index.html
- docs/components/menus/test.html
- docs/components/popovers/test.html
- docs/components/tooltips/test.html
- src/helix-ui/styles/components.less
- src/helix-ui/styles/components/menus.less
- src/helix-ui/styles/components/modals.less
- src/helix-ui/styles/components/popovers.less
- src/helix-ui/styles/components/search.less
- src/helix-ui/styles/components/tooltips.less
JIRA: surf-1570
fixes: https://github.com/rackerlabs/helix-ui/issues/449
> fix(#449): add css base styles with class to positionable elements

- docs/_data/nav.json5
- docs/_templates/application.njk
- docs/_templates/component.njk
- docs/_templates/element.njk
- docs/_templates/guide.njk
- docs/_templates/test.njk
- docs/docs.less
- docs/index.html
- src/helix-ui/styles/overrides.less
**NOTE:** This PR is likely to introduce unexpected styling in `docs/**/*.html` files. They will be corrected in subsequent PRs.
- clean up nav JSON
- add "breadcrumbs" block to all templates
- add "page_header" block to all templates
- tweak CSS for modified templates
> docs(*): update supporting files for upcoming docs updates

- docs/elements/hx-radio-set/index.html
- src/helix-ui/elements/HXRadioSetElement.js
- src/helix-ui/styles/components/radios.less
> refactor(hx-radio-set): refactor missing js props and documentation

- package.json
> chore(release): v0.16.0 [skip ci]

- docs/components/loader/index.html
- docs/components/loader/test-progress.html
(depends on updates from #500)
* Move Progress Bar tests to `docs/components/loaders/`
JIRA: n/a
> chore(tests): migrate Progress Bar tests

- docs/components/popover/test.html
- src/helix-ui/elements/HXPopoverElement.js
- src/helix-ui/elements/HXTooltipElement.js
- src/helix-ui/mixins/Positionable.js
* Fixes Issue #450 
* `<hx-popover>` open on render did not align popover properly.
> fix(#450): hx-popover open on render

- package.json
> chore(release): v0.16.1 [skip ci]

- src/helix-ui/styles/components/selectors.less
> fix(selector-strip): styles aligned with design side

- package.json
> chore(release): v0.16.2 [skip ci]

- docs/components/tabset/index.html
- docs/components/tabset/test.html
- src/helix-ui/elements/HXTabsetElement.js
> fix(Tabset): support nested tabsets

- docs/components/tabset/index.html
- docs/components/tabset/test.html
- package.json
- src/helix-ui/elements/HXTabsetElement.js
merge v0.16.3 patch back into master
> pull in v0.16.3 patch

- docs/components/file/file-tile-demo.js
> docs(typo): correct File Tile demo snippet

- docs/components/drawer/drawer-demo.js
> docs(Drawer): fix snippet typo

- docs/docs.less
> docs(CSS): adjust scope of `max-width` on `<p>`

- src/helix-ui/elements/HXCheckboxSetElement.js
- src/helix-ui/elements/index.js
* implement `<hx-checkbox-set>` which be will used as a wrapper for:
* Option (currently Choice) Tiles
* Selector Strip
> feat(checkboxes): implement <hx-checkbox-set>

- yarn.lock
* upgrade various HelixUI dependencies
> chore(yarn): upgrade various dev dependencies

- docs/styles/spec/text-input-spec.less
- docs/styles/spec/textarea-spec.less
Correct dirty + invalid + focus selector to apply correct box-shadow
JIRA: n/a
> docs(spec): fix spec LESS selectors

- package.json
> chore(release): v0.17.1 [skip ci]

- package.json
bump version with actual changes 🤦‍♂
> chore(release): v0.17.2 [skip ci]

- src/helix-ui/elements/hx-menuitem/index.js
- src/helix-ui/elements/index.js
> chore(src): reorganize Menu elements

- rollup.config.js
- scripts/_generate/index.js
- src/_bundle.umd.js
- src/browser-entry.js
* rename `src/browser-entry.js` to `src/_bundle.umd.js`
* move `HelixUI.initialize()` logic out of `rollup.config.js` into `src/_bundle.umd.js`
JIRA: SURF-1725
> Surf 1725 update entrypoints

- package.json
- yarn.lock
* patch dev dependencies
JIRA: N/A
> chore(yarn): patch dev dependencies

- src/less/components.less
- src/scss/components/_index.scss
- src/scss/components/alert/index.scss
Changes for 1874 Ticket for converting less to scss styles
> SURF-1874 Changes

- src/less/components/box/index.less
- src/scss/components/_index.scss
- src/scss/components/box/_index.scss
- src/scss/components/box/_mixins.scss
> refactor(styles): deprecate box LESS mixins for SCSS mixins

- src/less/components.less
- src/scss/components/_index.scss
- src/scss/components/badge/index.scss
Surf-1875 Changes converts less to scss styles.
> SURF-1875 Changes

- src/less/components.less
- src/scss/components/_index.scss
- src/scss/components/breadcrumb/index.scss
SURF-1876 Changes convert to Less to scss styles.
> SURF-1876 Changes

- scripts/start.js
> chore(pipeline): tweak watch globs

- package.json
> chore(release): v0.18.0-rc.0 [skip ci]

- src/less/components.less
- src/scss/components/_index.scss
- src/scss/components/pagination/_index.scss
JIRA: SURF-1880
Converting the less to scss styles and removing the pagination less file.
> Pagination: convert Light DOM LESS to SCSS

- src/less/components.less
- src/scss/components/_index.scss
- src/scss/components/pill/_index.scss
* refactor `Pill` Light DOM LESS -> SCSS
> refactor(pill): convert LESS to SCSS styles

- src/less/components.less
- src/scss/components/_index.scss
- src/scss/components/panel/_index.scss
> Panel: convert Light DOM LESS to SCSS

- src/less/components.less
- src/scss/components/_index.scss
- src/scss/components/navigation/_index.scss
> Navigation: convert Light DOM LESS to SCSS

- src/less/components.less
- src/scss/components/_index.scss
- src/scss/components/toast/_index.scss
> Toast: convert Light DOM LESS to SCSS

- src/less/components.less
- src/less/components/modal/index.less
- src/scss/components/_index.scss
- src/scss/components/layout/_index.scss
> Layout: convert Light DOM LESS to SCSS

- src/scss/components/_index.scss
> fix(css): add back navigation styles

- src/less/components.less
- src/scss/components/_index.scss
- src/scss/components/table/_index.scss
> Table: convert Light DOM LESS to SCSS

- .github/PULL_REQUEST_TEMPLATE.md
> chore: update github PR template

- src/less/components.less
- src/scss/components/_index.scss
- src/scss/components/modal/_index.scss
> Modal: convert Light DOM LESS to SCSS

- docs/components/_index.scss
- docs/components/menu/_spec.scss
- docs/docs.less
- src/less/components.less
- src/scss/components/_index.scss
- src/scss/components/menu/_index.scss
> Menu: convert Light DOM LESS to SCSS

- src/scss/components/menu/_index.scss
JIRA: n/a (white space corrections as reported by stylelint)
As long as TravisCI checks pass, this is good to merge.
> style: correct stylelint errors

- package.json
> publish(npm): v0.18.0-rc.1 [skip ci]

- src/less/components.less
- src/scss/components/_index.scss
- src/scss/components/radio/_index.scss
> refactor(Radio): convert Light DOM LESS to SCSS

- src/helix-ui/index.js
JIRA: n/a 
v0.14.x fix for issue #636
> [0.14.x] fix(initialize): remove wcr handler after first run

- src/helix-ui/index.js
JIRA: n/a 
v0.15.x fix for issue #636
> [0.15.x] fix(initialize): remove wcr handler after first run

- package.json
> chore(release): v0.15.1 [skip ci]

- src/helix-ui/index.js
JIRA: n/a 
v0.16.x fix for issue #636
> [0.16.x] fix(initialize): remove wcr handler after first run

- src/helix-ui/index.js
JIRA: n/a 
v0.17.x fix for issue #636
> [0.17.x] fix(initialize): remove wcr handler after first run

- package.json
> chore(release): v0.16.4 [skip ci]

- package.json
> chore(release): v0.17.3 [skip ci]

- src/utils/index.js
JIRA: n/a 
v0.18.x fix for issue #636
> [0.18.x] fix(onWebComponentsReady): remove wcr handler after first run

- package.json
> publish(npm): v0.18.0-rc.2 [skip ci]

- package.json
> Release v0.18.0

- LICENSE
- docs/_banner.scss
- docs/_layout.scss
- docs/_shame.scss
- docs/_templates/application.njk
- docs/_templates/element.njk
- docs/_templates/no-frame.njk
- docs/_test-content.scss
- docs/_toc.scss
- docs/components/layout/index.html
- docs/components/search/search-demo.js
- docs/docs.less
- docs/files/horizontal-layout-template.html
- docs/files/vertical-layout-template.html
- docs/guides/faq/index.html
- docs/guides/getting-started/index.html
- docs/index.html
- docs/index.scss
- gulpfile.esm.js
- package.json
- scripts/_config/index.js
- scripts/_generate/index.js
- tasks/archive/helix-ui.js
- tasks/archive/icons.js
- tasks/archive/index.js
- tasks/config.js
- tasks/index.js
- yarn.lock
JIRA: SURF-1958
* `*.tgz` extracts to `tmp/` directory
* icons tarball missing `LICENSE`
* helix-ui tarball missing polyfills, LICENSE, and other files shipped with NPM assets
* `*.tgz` extracts to correct directory
* icons tarball contains `LICENSE`
* helix-ui tarball mimics what is shipped to NPM
> Docs 0.18.0

- src/less/components.less
- src/scss/components/_index.scss
- src/scss/components/file/_config.scss
- src/scss/components/file/_hx-drop-fence.scss
- src/scss/components/file/_hx-drop-zone.scss
- src/scss/components/file/_hx-file-control.scss
- src/scss/components/file/_hx-file-icon.scss
- src/scss/components/file/_hx-file-tile.scss
- src/scss/components/file/_index.scss
* convert `file-input-spec.less` after `button-spec.less`
* current `file` Light DOM LESS will remain, until `file-input-spec.less` converted
> refactor(file): convert Light DOM LESS to SCSS

- package.json
> publish(npm): v0.18.1 [skip ci]

- LICENSE
- docs/_templates/application.njk
- docs/files/horizontal-layout-template.html
- docs/files/vertical-layout-template.html
* Update License Year Range
JIRA: SURF-1981
> chore(license): update year range

- package.json
> publish(npm): v0.19.0 [skip ci]

- package.json
new release - `HelixUI-v0.20.0`
> publish(npm): v0.20.0 [skip ci]

- .travis.yml
> fix(travis): update config

- docs/components/button/button-demo.js
- docs/components/button/index.html
- src/scss/components/button/mixins/_hxButton.scss
> refactor(button): tertiary button padding

- package.json
> publish(npm): v0.21.0 [skip ci]

- karma-init.js
- karma.conf.js
- src/elements/hx-alert/index.spec.js
- src/elements/hx-busy/index.spec.js
Initialize Karma only once
Just for fun
> Initialize Karma With Helix

- src/elements/hx-error/index.spec.js
Unit Test `<hx-error>`
Jira: SURF 2006 (Component Test)
> test(hx-error): unit test cases surf2006

- src/elements/hx-progress/index.spec.js
Unit Test `<hx-progress>`
Jira: SURF - 2017(Unit Test Cases)
> test(hx-progress): unit test cases surf2017

- .travis.yml
> chore(travis):  update config

- .travis.yml
Patch TravisCI for builds from a fork.
ref: https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
> chore(travis):  update config for build from a fork

- .travis.yml
Patch TravisCI for builds from a fork.
N/A
> chore(travis): update config for builds from a fork

- src/elements/hx-file-control/index.spec.js
Unit test `<hx-file-control>`
Jira: SURF-2007(unit test case)
> test(hx-file-control): surf-2007

- src/elements/hx-file-icon/index.spec.js
Unit test `<hx-file-icon>`
Jira: SURF-2008(unit test case)
> test(hx-file-icon): surf-2008

- src/elements/hx-div/index.js
- src/elements/hx-div/index.spec.js
Unit Test Case `<hx-div>`
Jira: SURF-2002
> test(hx-div): surf2002

- src/elements/hx-file-input/index.spec.js
unit test `<hx-file-input>`
Jira: SURF-2009(unit test case)
> test(hx-file-input): surf-2009

- src/elements/hx-select/index.spec.js
unit test `<hx-select>`
Jira: SURF-2024(unit test case)
> test(hx-select): surf-2024

- src/elements/hx-search/index.spec.js
unit test `<hx-search>`
Jira: SURF-2021(unit test case)
> test(hx-search): surf-2021

- src/elements/hx-pill/index.spec.js
Unit Test Case `<hx-pill>`
Jira: SURF 2015
> test(hx-pill test cases): surf2015

- src/elements/hx-menu/index.spec.js
unit test `<hx-menu>`
Jira: SURF-2012 (unit test case)
> test(hx-menu): surf-2012

- src/elements/hx-modal/index.spec.js
Unit Test Case `<hx-modal>`
Jira: SURF 2014
> test(hx-modal): surf2014

- src/elements/hx-menuitem/index.spec.js
Test case `<hx-menuitem>`
Jira: SURF 2013
> test(hx-menuitem test cases): surf2013

- src/elements/hx-file-tile/index.spec.js
unit test `<hx-file-tile>`
Jira: SURF-2010 (unit test case)
> test(hx-file-tile): surf-2010

- src/elements/hx-icon/index.spec.js
Test case `<hx-icon>`
Jira: SURF 2011
> test(hx-icon): implement component tests

- src/elements/hx-reveal/index.spec.js
Test Cases `<hx-reveal>`
Jira: SURF 2061
> test(hx-reveal): test cases SURF 2061

- src/elements/hx-radio-control/index.spec.js
Test Case `<hx-radio-control>`
Jira: SURF 2019
> test(hx-radio-control): test cases SURF2019

- src/elements/hx-select-control/index.spec.js
unit test `<hx-select-control>`
Jira: SURF-2025(unit test case)
> test(hx-select-control): surf-2025

- src/elements/hx-password-control/index.spec.js
Test Case `<hx-password-control>`
Jira: SURF-2056
> test(hx-password-control): component tests surf-2056

- src/elements/hx-popover/index.js
- src/elements/hx-popover/index.spec.js
Test Case `<hx-popover>`
Jira: SURF 2016
> test(hx-popover): component tests surf2016

- docs/components/email/email-control-demo.js
- src/elements/hx-email-control/index.spec.js
Test  Case `<hx-email-control>`
Jira: SURF 2055
> test(hx-email-control): test cases

- src/elements/hx-tab/index.spec.js
screenshot: `<hx-tab>` component tests
Failing Tests
Skipped Tests
Jira: SURF-2026 (unit test case)
> test(hx-tab): implement component tests surf-2026

- src/elements/hx-accordion/index.spec.js
Test Case `<hx-accordian>`
Jira: SURF 1994
> test(hx-accordian): implement component tests

- src/elements/hx-toast/index.spec.js
Unit test Case `<hx-toast>`
Jira: SURF-2033
> test(hx-toast): implement component tests

- src/elements/hx-tabcontent/index.spec.js
screenshot: `<hx-tabcontent>` component tests
Failing Tests
Skipped Tests
Jira: SURF-2027(unit test case)
> test(hx-tabcontent): implement component tests

- src/elements/hx-accordion-panel/index.spec.js
Test Case `<hx-accordion-panel>`
Jira: SURF-1995
> test(hx-accordion-panel): implement component tests

- package.json
Bump new version - HelixUI-v0.24.0
> publish(npm): v0.24.0 [skip ci]

- src/elements/hx-drop-fence/index.spec.js
Test Case `<hx-drop-fence>`
Jira: SURF 2004
> test(hx-drop-fence): implement component tests

- src/elements/hx-checkbox/index.spec.js
Test Case `<hx-checkbox>`
Jira: SURF-2000
> test(hx-checkbox): implement component tests

- src/elements/hx-checkbox-control/index.spec.js
Test Case `<hx-checkbox-control>`
Jira: SURF-1998
> test(hx-checkbox-control): implement component tests

- src/elements/hx-text-control/index.spec.js
Test Case `<hx-text-control>`
Jira: SURF 2031
> test(hx-text-control):  implement component tests

- src/elements/hx-textarea-control/index.spec.js
Test Case `<hx-textarea-control>`
Jira: SURF 2032
> test(hx-textarea-control): implement component tests

- src/elements/hx-drawer/index.spec.js
Test Case `<hx-drawer>`
Jira: SURF-2003
> test(hx-drawer): implement component tests

- src/elements/hx-drop-zone/index.spec.js
Test Case `<hx-drop-zone>`
Jira: SURF-2005
> test(hx-drop-zone): implement component tests

- src/elements/hx-checkbox-set/index.spec.js
Test Case `<hx-checkbox-set>`
Jira: SURF-1999
> test(hx-checkbox-set): implement component tests

- src/elements/hx-radio-set/index.spec.js
Test Case `<hx-radio-set>`
Jira: SURF-2020
> test(hx-radio-set): implement component tests

- docs/_data/nav.json5
- docs/components/switch/error-switch-demo.js
- docs/components/switch/index.html
- docs/components/switch/switch-demo.js
- docs/elements/hx-switch-control/index.html
- docs/elements/hx-switch/index.html
- src/elements/hx-switch-control/index.js
- src/elements/hx-switch/index.js
- src/scss/components/switch/_index.scss
> docs(hx-switch): Switch documentation

- src/elements/hx-tooltip/index.spec.js
Test Case `<hx-tooltip>`
Jira: SURF-2034
> test(hx-tooltip): implement component tests

- src/elements/hx-accordion/index.spec.js
Implement Stepper Component tests.  This is a CSS-based derivative of the `Accordion` Component.
Jira: SURF-2049
> test(stepper): implement component tests

- package.json
> publish(npm): v1.0.0 [skip ci]

- src/elements/hx-tabset/index.js
Accommodate Angular lifecycle for Issue #758.
Jira: SURF-2077
> feat(tabset): accommodate angular lifecycle

- docs/components/text-input/index.html
- docs/components/text-input/text-input-demo.js
- src/scss/components/text-input/_index.scss
Add Help Text and Error Text to `hx-text-control`
Jira: SURF-2065
> feat(hx-text-control): add help and error text

- package.json
> publish(npm): v1.1.0-rc.0 [skip ci]

- docs/components/beacon/index.html
- docs/components/topnav/index.html
- docs/components/topnav/test.html
- docs/components/topnav/topnav-demo.js
- src/scss/components/_index.scss
- src/scss/components/topnav/index.scss
- src/scss/components/topnav/mixins/_topNavControl.scss
Revise `hxTopNav` component styles.
Jira: SURF-2080
> feat(topnav): revise component styles

- docs/components/_index.scss
- docs/components/icon/_index.scss
- docs/components/navigation/_index.scss
- docs/docs.less
Icon and Nav Dev Docs from LESS to SCSS
Jira: SURF-1987
> refactor(icon and nav): icon and nav dev docs from less to scss

- src/scss/components/dropdown-select/mixins/SelectControl.scss
Broken styling of disabled Dropdown Select in Chromium-based browsers
Jira: SURF-2081
> fix(dropdown-select): disabled state for chromium-based browsers

- docs/components/navigation/index.html
- docs/components/secnav/index.html
- docs/components/secnav/secnav-demo.js
- docs/components/secnav/test.html
- docs/components/topnav/index.html
- docs/components/topnav/test.html
- docs/components/topnav/topnav-demo.js
- src/elements/hx-disclosure/index.spec.js
- src/elements/hx-select/_shadow.scss
- src/scss/components/secnav/index.scss
Patch navigation component demos, and preps for `HelixUI-v1.1.0` release.
Jira: SURF-2089
> feat(release): tweak navigation component demos

- package.json
> publish(npm): v1.1.0 [skip ci]

- docs/components/_index.scss
- docs/components/panel/_index.scss
- docs/components/panel/_spec.scss
- docs/docs.less
Refactor Panel Dev Docs from LESS to SCSS
Jira: SURF-2083
> docs(scss): refactor panel less dev doc styles to scss

- docs/components/secnav/index.html
- docs/components/secnav/secnav-demo.js
- docs/components/secnav/test.html
- src/scss/components/secnav/index.scss
Design Review for `Secondary Navigation` component.
Jira: SURF-2092
> feat(secnav): design review for secondary navigation component

- package.json
> publish(npm): v1.2.0 [skip ci]

- README.md
- docs/index.html
In preparation for major updates, moving legacy `HelixUI-v1.x` documentation.
Jira: SURF-2141
> feat(v1.x): HelixUI-v1.x documentation

- package.json
* typography and color updates
> publish(npm): v2.0.0-rc.0

- src/scss/components/breadcrumb/index.scss
Implement and Document variables and attributes
Jira: SURF-2100
> docs(hx-breadcrumb): implement and document vars and attrs

- src/scss/components/list/_index.scss
`<hx-list >`: implement and document variables and attributes
Jira: SURF-2111
> docs(list): implement and document vars and attrs

- .travis.yml
* patch config
Jira: SURF-2162
> chore(config): patch config

- src/scss/components/breadcrumb/index.scss
Update `Breadcrumb` component specifications.
Jira: SURF-2150
> feat(breadcrumb): update component specs

- src/scss/components/checkbox/_index.scss
- src/scss/components/checkbox/mixins/_hxCheckboxControl.scss
- src/scss/components/checkbox/mixins/_hxCheckboxFacade.scss
- src/scss/components/radio/mixins/_hxRadioControl.scss
- src/scss/components/radio/mixins/_hxRadioFacade.scss
Update `Checkbox` specifications.
Jira: SURF-2149
> feat(checkbox): update component specs

- src/scss/components/email/_index.scss
`<hx-emailControl>`: Implement and Document attributes and variables.
Jira: SURF 2106
> docs(email): implement and document vars and attrs

- src/scss/components/email/_index.scss
Update `Email` component specifications.
Jira: SURF-2156
> refactor(email): update component specs

- src/scss/components/password-input/_index.scss
Update `Password` component specifications.
Jira: SURF-2157
> refactor(password): update component specs

- package.json
> publish(npm): v2.0.0-rc.1

- src/scss/components/tabset/_index.scss
<hx-tab> implementing color palette styles
Jira: SURF-2151
> feat(tabset): new component specs

- docs/_data/nav.json5
- src/scss/base/_typography.scss
- src/scss/components/checkbox/_index.scss
- src/scss/components/pill/_index.scss
- src/scss/components/radio/_index.scss
Minor tweaks based on user feedback from our Release Candidates.
Jira: SURF-2167
> chore(releases):  update component specs based on feedback

- package.json
> publish(npm): v2.0.0

- src/scss/components/tabset/_index.scss
`<hx-tabset >` : Implement and document attributes and variables
Jira: SURF-2160
> docs(tabset): implement and document attrs and vars

- package.json
> publish(npm): v2.1.0

- src/scss/components/password-input/_index.scss
`<hx-passwordinput>` : implement and document attributes and variables
Jira: SURF2120
> docs(password): implement and document attrs and vars

- src/scss/components/loader/_hx-progress.scss
`<hx-loader>` : Implement and Document attributes and variables
Jira: SURF2112
> docs(loader): implement and document vars and attrs

- src/scss/components/pagination/_index.scss
`<hx-pagination>` : implement and document attributes and variables
Jira: SURF-2118
> docs(pagination): implement and document attrs and vars

- src/scss/components/button/mixins/_hxButton.scss
`<hx-button>`: primary button changes
Jira: SURF2179
> style(button): primary button styling changes

- src/scss/components/panel/_index.scss
`<hx-panel>` : implement and document attributes and variables
Jira: surf-2119
> docs(panel): implement and document attrs and vars

- docs/components/icon/_index.scss
- src/elements/hx-toast/_shadow.scss
- src/scss/components/alert/index.scss
- src/scss/components/badge/index.scss
- src/scss/components/form/_deprecated.scss
- src/scss/components/selector-strip/_hxSelector.scss
- src/scss/components/switch/mixins/_hxSwitchControl.scss
- src/scss/components/toast/_index.scss
Update the default `Invalid` and `Error` state color to v2.0 specifications.
Jira: SURF-2191
> fix(invalid): update default color

- src/scss/components/button/mixins/_hxButton.scss
Patch for Primary Button- hover state.
Jira: SURF-2179
> fix(button): primary hover state

- src/elements/hx-pill/_shadow.scss
- src/scss/components/pill/_index.scss
`<hx-pill>` : implement and document attributes and variables
Jira: SURF-2121
> docs(pill): implement and document attrs and vars

- src/scss/components/search/SearchFacade.scss
- src/scss/components/search/_index.scss
`<hx-search>` : feedback changes
Jira: SURF 2180
> style(search): feedback changes

- src/scss/components/topnav/index.scss
- src/scss/components/topnav/mixins/_topNavControl.scss
`<hx-topnav>` : implement and document attributes and variables
Jira: SURF 2115
> feat(topnav): document styles and update component specs

- .github/workflows/build.yml
* Modify CI Pipeline
* Implement GitHub Actions (BETA)
Jira: SURF-2192
> build(ci): implement github actions

- .github/workflows/build.yml
* GitHub Action `buld.yml` patch
Jira: SURF-2192
> build(ci): gh actions patch

- package.json
> publish(npm): v2.2.0

- .github/workflows/browser-tests.yml
- .github/workflows/build.yml
- karma.sauce.config.js
* Migrate SauceLabs CI to GitHub Actions
Jira: SURF-2163
> build(sauce): migrate to github actions

- package.json
> publish(npm): v2.3.0-rc.0

- docs/components/secnav/index.html
- docs/components/secnav/test.html
- src/scss/components/secnav/index.scss
* Secondary Navigation - iterate specs
Jira: SURF-2198
> chore(secnav): iterate specs

- package.json
> publish(npm): v2.3.0-rc.1 

- src/scss/components/button/_buttonSet.scss
- src/scss/components/button/mixins/_hxButton.scss
`<hx-button>`: Fabric changes
Jira: SURF 2185
> style(button): update tertiary button specs

- src/scss/components/tabset/_index.scss
`<hx-tabset>`: refactor with design tokens
Jira: SURF 2205
> refactor(tabset): implement design tokens

- src/scss/components/checkbox/_index.scss
- src/scss/components/checkbox/mixins/_hxCheckboxControl.scss
- src/scss/components/checkbox/mixins/_hxCheckboxFacade.scss
`<hx-checkbox>`: refactor with design tokens
Jira: SURF-2201
> refactor(checkbox): implement design tokens spec

- src/scss/components/text-input/_index.scss
`<text-input>` : implement design tokens styles
Jira: SURF-2203
> refactor(text-input): implement design tokens spec

- docs/components/secnav/test.html
- src/scss/components/secnav/index.scss
- src/scss/components/topnav/index.scss
Secondary Navigation - implement additional feedback.
Jira: SURF-2198
> refactor(secnav): implement feedback

- LICENSE
- README.md
- docs/files/horizontal-layout-template.html
- docs/files/vertical-layout-template.html
* Add GitHub Action Badges
* Update license year
Jira: SURF-2209
> docs(actions): add badges update year

- docs/_templates/application.njk
* Update license year
Jira: SURF-2209
> chore(docs): update license year

- package.json
> publish(npm): v2.3.0

- src/elements/hx-toggle/_shadow.scss
`<hx-toggle>`: Alignment fixes for toggle 
Jira: SURF 2210
> style(toggle): alignment changes for grid and list icons

- src/scss/components/search/SearchFacade.scss
- src/scss/components/search/_index.scss
`<hx-search>` : implement and document variables and attributes
Jira: SURF-2125
> styles(search): implement and document variables and attributes

- src/scss/components/toast/_index.scss
`<hx-toast>` : Implement and document variables and attributes
Jira: SURF-2132
> refactor(toast): implement and document variables and attributes

- src/scss/components/switch/_index.scss
- src/scss/components/switch/mixins/_hxSwitchControl.scss
`<hx-switch>` : Implement and document variables and attributes
Jira: SURF 2128
> docs(switch): implement and document variables and attributes

- .travis.yml
* Need to look into this.
Jira: SURF-2195
> chore(pipeline):  comparing builds

- src/scss/components/selector-strip/_hxSelector.scss
`<hx-selectorstrip>` : implement and document variables and attributes
Jira: SURF2126
> refactor(selector-strip): implement and document variables and attributes

- src/scss/components/layout/_index.scss
`<hx-layout>` : Implement and document variables and attributes
Jira: SURF 2110
> refactor(layout): implement and document variables and attributes

- docs/components/navigation/index.html
- src/scss/components/navigation/_index.scss
`<navigation>` : implement left navigation new fabric styles
Jira: Navigation-SURF-2172
> refactor(navigation): implement left navigation new specs

- src/scss/components/menu/_index.scss
* add `IE11` fallbacks
Jira: SURF-2188
> docs(menu): add IE11 fallbacks

- src/elements/hx-accordion-panel/_shadow.scss
- src/scss/components/accordion/_stepper.scss
* Add fallbacks
Jira:
* SURF-2188
* SURF-2127
> docs(stepper): add fallbacks

- README.md
> chore(readme): add test build instructions

- package.json
> publish(npm): v2.4.0-rc.0 
