HelixDesignSystem/helix-ui

source/_templates/partials/head.njk, source/components/icon/HxIcon.less, source/components/icon/hx-icon.less, source/helix-ui.less
JIRA: n/a
For polyfilled browsers, before an icon element upgrades, it is empty and has a `0x0 px` dimension. This causes surrounding content to jump around as icons are upgraded (getting proper styles).
BEFORE | AFTER
----- | -----
The `0x0 px` styling (when empty) was removed so that icon elements reserve the space for their SVG images and retain content flow.
An icon defaults to `1x1 em`, which usually computes to `16x16 px`. However, in scenarios where an icon is contained within an element that shrinks for responsiveness, the icon would shrink smaller than `1x1 em`.
=> Fix Icon Styling

source/components/text-input/index.html, source/components/text-input/text-input.less
JIRA: n/a
* Update Text Inputs component to behave in an additive manner rather than overwriting non-Helix styles (i.e. convert to CSS class).
* Simplify demo
* tweak styles for `textarea`
=> Refactor text inputs

source/_less/reset.less, source/components/HxElement.less, source/components/checkbox/HxCheckbox.less, source/components/reveal/HxReveal.html, source/components/reveal/HxReveal.less, source/components/tabset/HxTabpanel.less, source/components/tabset/HxTabset.less, source/components/tabset/index.html, source/docs.less, source/helix-ui.less
Correct styling bug. This bug isn't present in polyfilled browsers.
CSS inheritance includes the `<slot>` element in the Shadow DOM (See [Slots and Slotted Elements in a Shadow Tree](https://drafts.csswg.org/css-scoping/#slots-in-shadow-tree)). As such, several css properties that we thought we're being inherited from the light DOM are incorrect. To correct, I've set up a generic `HxElement.less` file that will handle common resets needed to build custom elements.
_The two paragraphs in the tab should share half the width._
=> fix(CSS): correct style inheritance with <slot>

bin/start.js, source/_templates/component.njk, source/components/grid/grid-docs.less, source/components/grid/grid.less, source/components/grid/index.html, source/components/icon/index.html, source/components/tabset/index.html
JIRA: https://jira.rax.io/browse/SURF-623
* `.hx{modifier}[-{size}]-{N}` renamed to `.hx{modifier}-{N}[-{size}]`
* optional piece moved from _middle_ to _end_ of class name
* `.hxCol` split into `.hxCol` and `.hxSpan-{N}[-{size}]`
* separates _content layout_ from _container sizing_
* `.hxCol` no longer applies a columnar flexbox layout. 
* The majority of the time this is unneeded.
* It changed some built-in browser behavior (margin collapsing; caused more space than necessary to be added to the document).
* added `.hxRow.hxGutterless` styling
* clarified documentation
* Container and width modifier classes were tightly coupled (can't use width modifiers without turning an element into a Column container).
* Documentation unclear when to use Row and Column containers.
* Modifier classes …
=> SURF-623: Modify Grid

source/components/checkbox/HxCheckbox.less, source/components/checkbox/checkbox.less, source/components/icon/hx-icon.less, source/components/table/index.html
* Also corrected vertical alignment in context with surrounding text.
JIRA: (part of) https://jira.rax.io/browse/SURF-623
=> refactor(checkbox): reserve geometry as it upgrades

source/_data/nav.yml, source/components/description-list/description-list.less, source/components/description-list/index.html, source/helix-ui.less
JIRA: https://jira.rax.io/browse/SURF-80 
This is the work for the Key/Value Lists. During development we were using the HTML description lists and suggested that perhaps this should just be titled Description List.
=> feat(definition list): Build Key Value Lists

.travis.yml, lib/publish.js, package.json
Correct `package.json` issues pertaining to NPM release.
* no auto ghpages
* add version to ghpages commit message
* don't use postinstall for dev setup (causes errors when installing)
* reduce scope of "clean" task
JIRA: https://jira.rax.io/browse/SURF-673 (-ish)
=> fix(package): tweak scripts

src/helix-ui/elements/HXDisclosureElement.js, src/helix-ui/elements/HXMenuElement.js, src/helix-ui/elements/HXPopoverElement.js, src/helix-ui/elements/HXTooltipElement.js
* When elements are in LightDOM, `getRootNode()` will return the `document`.
* When the elements are composed inside a shadow root, `getRootNode()` will return the `shadowRoot`.
JIRA: n/a
=> fix(getRootNode): correct root node element lookup

src/helix-ui/elements/_hx-element.less
Removes the built-in "X" from text inputs in IE and Edge.
=> fix(Search): remove built-in X in IE and Edge

src/helix-ui/styles/core/hx-accordion-panel.less
Closes #168
Screenshots are from Firefox 59 (polyfilled). I verified that the corrected styles still work on IE11 and Edge 16.
_panels disappear when closed_
_panels collapse when closed_
=> fix(Accordion): correct CSS in polyfilled browsers

src/helix-ui/styles/modules/choice-tiles.less
* Prevent browsers from jumping to top of page when selecting a Choice Tile.
JIRA: https://jira.rax.io/browse/SURF-1011
The browser should not scroll when I click a Choice Tile.
Browser | Before | After
----- | ----- | -----
Chrome | ![chrome-before-broke](https://user-images.githubusercontent.com/545605/38114707-046fafaa-336f-11e8-9fc2-13f313a9135d.gif) | ![chrome-after-works](https://user-images.githubusercontent.com/545605/38114720-0a87e8f8-336f-11e8-8a30-3ddcf949241b.gif)
Firefox ⭐️ | ![firefox-before-works](https://user-images.githubusercontent.com/545605/38114729-141b1d86-336f-11e8-9cae-07a5133f5aa1.gif) | ![firefox-after-works](https://user-images.githubusercontent.com/545605/38114731-194e74ce-336f-11e8-9e15-9dceb12c71a9.gif)
Safari ⭐️ | …
=> fix(Choice Tiles): correct focus bug

docs/_templates/partials/after_footer.njk, docs/components/layouts/horizontal-layout-template.html, docs/components/layouts/vertical-layout-template.html, rollup.config.js, src/helix-ui/elements/HXElement.js, src/polyfills.js, src/polyfills/Object.js
* (HXElement) Update `$emit()`
* Do NOT bubble events by default
* Provide capability to override event configuration.
* (polyfills) Add `Object.assign()` polyfill.
* (Layouts) Update layout templates to include minified polyfill
* (docs) include polyfills in templates
Before | After
----- | -----
=> fix(events): Emit non-bubbling events by default

src/helix-ui/styles/mixins.less
Per discovery in slack discussion, the implemented color for placeholders doesn't match what was agreed upon in bowling on March 1 and March 13, 2018.
=> fix(CSS): correct placeholder color

src/helix-ui/styles/components/lists.less
JIRA: https://jira.rax.io/browse/SDP-993
According to this [Stack Overflow post](https://stackoverflow.com/questions/21600345/flexbox-and-internet-explorer-11-displayflex-in-html), IE11 interprets default flex values a bit differently than other browsers. You can duplicate the problem by navigating to the `List` component demo in IE11 and checkoff `Vertical` view. You will see the text overlapped. By adding these lines of code, this correctly sets the flex values for IE11, and does not adversely affect Chrome or Firefox.
=> fix(CSS) Change flex values for IE11 support

docs/components/grid/index.html
Fix broken styles of "Responsive Options" table in Grid component documentation
before | after
----- | -----
=> docs(Grid): fix responsive options table

package.json, yarn.lock
Per Slack discussion. We're making `@webcomponentsjs/webcomponents` a peer dependency to remove the hard requirement from the toolkit.
=> chore(npm): make @webcomponentsjs/webcomponents a peer dependency

lib/copy.js
remove `vendor` from copied directories (no longer present)
=> chore(pipeline): fix build warning

package.json, yarn.lock
Less 3.x has a bug that prevents the correct CSS from being generated
when the `less` object in node is reused and the entry point hasn't
changed (CSS changes only exist in `@import`ed files).
The first compile works as expected, but subsequent compiles are broken.
This is causing issues with our build pipeline when updating styles
and the development server is running. Currently, you have to restart
the development server to see the updated styles.
See https://github.com/less/less.js/issues/3185
=> chore(pipeline): downgrade to less@2.x

.github/ISSUE_TEMPLATE/bug-report.md, docs/_templates/partials/global_nav.njk, docs/docs.less, src/helix-ui/styles/components/buttons.less
Once merged, we'll be able to create a new bug report using a link in the documentation's global header.
=> chore(github): Add Bug Report issue template

docs/components/layouts/index.html, docs/components/typography/index.html, docs/guides/getting-started/index.html, src/helix-ui/styles/base/typography.less, src/helix-ui/styles/components/tables.less, src/helix-ui/styles/components/typography.less, src/helix-ui/styles/overrides.less
* `caption` -> `.hxTable caption`
* `figcaption` -> `.hxFigure figcaption` (may still need tweaking in future)
* `.hxCaption` updated to adhere to current specs
* Better Typography docs for Headings, Caption, Sub-Body, and Subdued
JIRA: n/a
Preview: https://deploy-preview-292--helix-ui.netlify.com/
Demo | BEFORE | AFTER
----- | ----- | -----
Headings | <img width="745" alt="headings-before" src="https://user-images.githubusercontent.com/545605/43172400-bc92a928-8f74-11e8-8703-c0ecadbb5395.png"> | <img width="746" alt="headings-after" src="https://user-images.githubusercontent.com/545605/43172399-bc7de970-8f74-11e8-9693-bb407cb566b2.png">
Subdued | <img width="750" alt="subdued-before" src="https://user-images.githubusercontent.com/545605/43172409-c90ea4ae-8f74-11e8-9cf8-03ec9ecd79f9.png"> …
=> fix(CSS): correct caption resets

docs/components/popovers/test.html, docs/components/tooltips/test.html, src/helix-ui/elements/HXPopoverElement.js, src/helix-ui/elements/HXTooltipElement.js
* Correct logic to wrap attribute value with quotes, within querySelector() calls.
Closes #303
=> fix(*): Fix Popover and Tooltip

docs/elements/hx-busy/index.html, docs/elements/hx-checkbox/index.html, docs/elements/hx-pill/index.html
* add documentation that `<hx-busy>` is an inline element
* add documentation that `<hx-pill>` is an inline element
* add documentation that `<hx-checkbox>` is an inline element
* add reference to significant white space section in react compatibility guide for above
Closes:
* SURF-1267 (JSX: Busy)
* SURF-1270 (JSX: Checkbox)
* SURF-1287 (JSX: Pills)
=> docs(*): annotate usage inline and add react compatibility ref 

src/helix-ui/styles/elements/hx-tab.less, src/helix-ui/styles/elements/hx-tabcontent.less, src/helix-ui/styles/elements/hx-tablist.less
* ~~`<hx-popover-foot>`: set `display` property to `flex`~~
* `<hx-tablist>`: set `display` property to `flex`
* `<hx-tab>`: set all tabs to a `left-margin` of `0.25rem`
JIRA: 
~~* SURF-1290: JSX: Popovers~~ (deprecating `<hx-popover-foot>`)
* SURF-1292: JSX: Tabs
=> style(less): surf-1290-1292 update styles for JSX compatibility

package.json
Relates to changes of the layout templates in #327 
Older versions of `@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js` ironically used ES6 syntax to convert ES5 constructor functions back into ES6 classes for use in modern browsers (i.e., any browser that _isn't_ Internet Explorer). This would throw an error if loaded in IE, so hacks had to be used to detect modern browsers in order to remove the adapter before it has a chance to load in IE (which didn't always work).
Version `1.2.4` and `2.0.4` (released 2018-08-01), fixes the adapter by simplifying its consumption.
Browser detection is baked-in (no need for `<span>` hack), which also eliminates errors being thrown in IE.
Instead of this:
```html
<span id="ce-es5-adapter">	
<script>	
if (!window.customElements) {	
var …
```
=> chore(deps): update peerDependencies

docs/components/files/test-file-selectors.html, docs/components/files/test-file-tiles.html, src/helix-ui/elements/HXFileTileElement.js
* fixed summited for Issue https://github.com/rackerlabs/helix-ui/issues/322
* do not escape truncated long file names
* fix minor typo
JIRA: SURF-1356
Closes #322
=> fix(hx-file-tiles): SURF-1356 and bug fix Issue-322

docs/_data/polyfilled-apis.json5
Firefox 63 supports `Element.attachShadow()`, `Element.shadowRoot`, and `Window.customElements`
JIRA:
=> Update Polyfills table to reflect Firefox 63 capabilities

docs/elements/hx-search-assistance/index.html, src/helix-ui/elements/HXSearchAssistanceElement.js
* implement new positioning logic
* update event listeners, so that they are added only when `<hx-search-assistance>` is opened
* update event listeners, so that they are removed when `<hx-search-assistance>`  is closed
* update `<hx-search-assistance>` documentation with the positioning logic properties
=> feat(hx-search-assistance): implement new positioning logic

src/helix-ui/elements/HXTabsetElement.js
* Temporary fix #334, IE11 and Edge Tabs bug.
* Future spike needed to properly handle event propagation for `HelixUI` custom elements.
JIRA: SURF-1396
=> fix(tabset): surf-1396 (issue #334) IE11 and Edge Tabs bug

docs/elements/hx-menu/index.html, src/helix-ui/elements/HXMenuElement.js
* Refactored `HXMenuElement` to make use of the `Positionable` mixin.
JIRA: SURF-1497
=> refactor(hx-menu): surf-1497 use positionable mixin

src/helix-ui/elements/HXPopoverElement.js, src/helix-ui/elements/HXTooltipElement.js
* update HXTooltipElement to wait until connected before
attaching behavior to its controlElement
* update HXPopoverElement to default attrs on connect,
not in the constructor
Fixes #406
=> fix(*): Fix React compatibility

src/polyfills/Node.js, src/polyfills/index.js
Removing, because `@webcomponents/shadydom` polyfill [already includes](https://github.com/webcomponents/shadydom/blob/master/src/patches/Node.js#L160-L184) the `Node.prototype.isConnected` polyfill.
JIRA: n/a
=> revert(polyfills): remove unnecessary isConnected polyfill

docs/components/popovers/test.html, docs/components/tooltips/test.html, src/helix-ui/elements/HXDisclosureElement.js, src/helix-ui/elements/HXTooltipElement.js, src/helix-ui/mixins/Positionable.js
**HTML5**
https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute
> The id attribute specifies its element's unique identifier (ID).
> There are no other restrictions on what form an ID can take;
in particular, IDs can consist of just digits, start with a digit,
start with an underscore, consist of just punctuation, etc.
**HTML4.01**
https://www.w3.org/TR/html401/types.html#type-id
> ID and NAME tokens must begin with a letter ([A-Za-z]) and
may be followed by any number of letters, digits ([0-9]),
hyphens ("-"), underscores ("_"), colons (":"),
and periods (".").
JIRA: n/a
=> fix(Positionable): correct support for HTML5 IDs

docs/components/buttons/index.html, docs/components/buttons/test.html
Closes #426
**Buttons Component (Before)**
**Buttons Component (After)**
**Buttons Test (new)**
=> docs(Buttons): clarify need for span around text node children

docs/components/alerts/index.html, docs/components/box/index.html, docs/components/buttons/index.html, docs/components/checkboxes/index.html, docs/components/choice-tiles/index.html, docs/components/dropdown-select/index.html, docs/components/files/index.html, docs/components/icons/index.html, docs/components/lists/index.html, docs/components/loaders/index.html, docs/components/modals/index.html, docs/components/panels/index.html, docs/components/pills/index.html, docs/components/popovers/index.html, docs/components/reveals/index.html, docs/components/search/index.html, docs/components/tables/index.html, docs/components/text-inputs/index.html, docs/components/toasts/index.html, docs/components/tooltips/index.html
* remove usage of `<hx-select></hx-select>`
* except for Dropdown Select component (to be updated in separate PR)
* remove incorrect usage of `<hx-radio>`
* remove incorrect usage of `<hx-checkbox>`
JIRA: n/a
=> [^459] docs(*): semi-revert demo config form refactor

docs/components/checkboxes/test.html, docs/docs.less, docs/styles/spec/checkbox-spec.less, src/helix-ui/styles/components/checkbox.less
JIRA: surf-1624
When comparing the screenshots below, Dirty (in the after screenshots) should replace the Changed and Touched (in the before screenshot). Invalid styles should match.
[test page before screenshot](https://user-images.githubusercontent.com/10750223/56598941-1fe67f00-65bb-11e9-9613-20b96ccb1665.png)
[test page after screenshot](https://user-images.githubusercontent.com/10750223/56598967-283eba00-65bb-11e9-9304-5655b1d92991.png)
=> refactor(Checkbox): phase 2.5 CSS refactoring

docs/components/box/index.html, docs/components/box/test.html, src/helix-ui/elements/HXDivElement.less
* Fixes Issue #444 
* `<hx-div>` box-sizing inheritance
=> fix(#444): hx-div box-sizing inheritance

docs/guides/faq/index.html, docs/guides/getting-started/index.html, docs/guides/polyfills/index.html, docs/guides/react-compatibility/index.html
- move page description into page_header (if it makes sense)
- removed usage of `p.comfortable` styling
- add TODO comments to mark tasks for future updates
- update markup to be more semantic
JIRA: n/a
=> docs(guides): content and markup tweaks

docs/components/tabset/index.html, docs/components/tabset/tabset-demo.js, docs/docs.js, docs/docs.less, docs/elements/hx-tabset/index.html, src/helix-ui/elements/HXTabsetElement.js, src/helix-ui/styles/components/buttons.less, src/helix-ui/styles/overrides.less
* add `update()` to `HXTabsetElement` to enable manual synchronization of visual appearance with configured state
* fix `hxtabclick` listener to update visual state if configuration is already correct
* tweak `hr.hxDivider` style to work on various background colors
* add spacing styles for button sets (beta)
JIRA: SURF-1569
Relates to #443
=> feat(HXTabsetElement): improve support for dynamic tabs

docs/components/radio/index.html, docs/components/radio/radio-basic-demo.js, docs/components/radio/test.html, docs/docs.js
* add a basic radio demo:
```html
<hx-radio-set>
<input id="radBasicDemo" type="radio" />
<label for="radBasicDemo">
<hx-radio></hx-radio>
Radio Label
</label>
</hx-radio-set>
```
* add `Visually Invalid` label for `class="hxInvalid"` styles
* update Test Page to include tests for:
- Pristine State:
* `Optional, Enabled, Focused, Invalid`
* `Required, Enabled, Focused, Invalid`
- Dirty State:
* `Optional, Enabled, Focused, Invalid`
* `Required, Enabled, Focused, Invalid`
- Visually Invalid State:
* `Optional, Enabled, Focused, Invalid`
* `Required, Enabled, Focused, Invalid`
=> feat(radio): add basic demo and enabled-focus-invalid tests

docs/components/box/index.html, docs/components/button/index.html, docs/components/file/index.html, docs/components/modal/index.html, docs/components/table/index.html, src/helix-ui/styles/components/radios.less
* add missing `<hx-radio-set>` elements to the following demo pages:
* box
* button
* file
* modal
* table
=> fix(radios): add missing demo page <hx-radio-set> elements

docs/_templates/no-frame.njk, docs/components/menu/test-positioning.html, docs/docs.less, docs/styles/spec/menu-positioning-spec.less, src/helix-ui/utils/alignment.js
Add "start" and "end" alignment support for smart repositioning.
fixes #528
* notice how the menus in the corners extend beyond the viewport
See https://deploy-preview-530--helix-ui.netlify.com/components/menu/test-positioning.html
* corner menus are properly positioned within the viewport
=> fix(alignment): correct "smart" repositioning alignment

src/less/components/breadcrumb/index.less
JIRA: SURF-1772
1. Applied spacing as per the design spec.
2. As per the design spec, title case needs to be applied for the text string in root or child nodes in the breadcrumb. text-transform: capitalize does not get applied on capital string and/or on capital letters within the words in breadcrumb string. For now, Applied fix to change only the first letter of the text string to capital.
3. Changed CSS properties order just to reflect box model first.
4. Ignored about ellipses for lengthier string as the anchor element is anyhow inline element and the text flows in to next line.
Please include Design LGTM, if approval required on the second point above.
=> Changes to Breadcrumb as per design spec

src/less/components.less, src/scss/components/_config.scss, src/scss/components/_index.scss, src/scss/components/tooltip/_index.scss
* add `src/scss/components/_hxComponent.scss` with %hxComponent placeholder styles
* convert Tooltip to SCSS in order to verify %hxComponent implementation
JIRA: SURF-1893 (also SURF-1902)
*extending `%hxComponent`* (new CSS on left)
*remaining `hx-tooltip` styles* (new CSS on left)
=> refactor(src): deprecate .hxComponent in LESS

src/interfaces/HXElement/index.js
- move `ShadyCSS.styleElement()` from constructor to `connectedCallback()`
Fixes #656 
JIRA: SURF-1977
=> [v0.18.x] fix(HXElement): call ShadyCSS away from constructor

docs/guides/getting-started/index.html
Change all references to `public/assets` to `public/vendor` when referencing HelixUI or polyfill assets.
* `public/assets` - code _you_ have written
* `public/vendor` - code _others_ have written
=> docs(Getting Started): assets -> vendor

docs/_templates/application.njk
The date provided does not correlate to release date.
=> chore: remove docs homepage date updated

docs/_data/nav.json5, docs/components/accordion/index.html, docs/components/stepper/index.html, src/elements/hx-accordion-panel/_shadow.scss, src/scss/components/accordion/_stepper.scss
=> refactor(stepper content): surf1307

docs/components/drawer/index.html, docs/components/drawer/slotted-drawer-demo.js, docs/docs.js
=> fix(new working example for drawer): surf1971

.github/PULL_REQUEST_TEMPLATE.md, .travis.yml, karma-init.js, src/elements/hx-busy/index.js, src/elements/hx-busy/index.spec.js
Adding additional tests to `<hx-busy>`:
* add more describe blocks
* add component specific tests
Also:
* update pull request template
* update `TravisCI` config.
Jira: SURF-2051
=> test(hx-busy): restructure and add additional tests

.travis.yml, karma-sauce-init.js, karma.sauce.config.js, package.json, src/elements/hx-error/index.spec.js
* Implemented automated browser testing in the following:
* Chrome
* Firefox
* Safari
* Edge
* IE11
* Runs full suite of tests in our TravisCI pipeline for each pull request.
* Initial prototype for UI automated testing.
* **NOTE:** We still need to manually check UI updates in the above supported browsers.
Jira: SURF-2050
=> test(ui): implement automated browser testing

src/elements/hx-alert/index.spec.js
Restructure and add additional component tests.
Jira: SURF-2052
=> test(hx-alert): restructure and add more tests

karma.sauce.config.js, src/elements/hx-alert/index.spec.js
Patching `<hx-alert>` for IE11, legacy Edge, and older browsers.
Jira: SURF-2052
=> test(hx-alert): add check for IE11, legacy Edge

README.md
Migrated `HelixUI` repo to from `TravisCI` `.org` to newer `.com` infrastructure.
This allows us to use GitHub Apps, which provides richer detail for Pull Requests.
SURF-2059
=> perf(travis): migrate to travis-ci.com infrastructure

package.json
Version bump.  New `HelixUI` release.
=> publish(npm): v0.22.0 [skip ci]

karma.sauce.config.js, src/elements/hx-disclosure/index.spec.js
* `<hx-disclosure>` component tests
* Add SauceLabs builds to group test results.
Jira: SURF-2001
=> test(hx-disclosure): add component tests and sauce builds

package.json
Version bump.  `HelixUI-v0.23.0` release.
=> publish(npm): v0.23.0 [skip ci]

src/elements/hx-search-control/index.js, src/elements/hx-search-control/index.spec.js
Test Case `<hx-search-control>`
Jira: SURF 2062
=> feat(hx-search-control): add event listener and component tests

src/elements/hx-radio/index.spec.js
Test Cases `<hx-radio>`
Jira: SURF2018
=> test(hx-radio): test cases

docs/guides/faq/index.html
"ESM for Modern Bundlers" is actually...
* **module:** ESM
* **syntax:** ES2015+ / ES6+
=> docs(faq): fix typo

src/elements/hx-tablist/index.spec.js
* implement `<hx-tablistl>` component tests
* add FAILING tests to replicate HelixUI Issue #516 bugs
* **Once the dynamic tab bug patch is implemented, we will include these tests with our test run.**
Jira: SURF-2028
=> test(hx-tablist): implement component tests

src/elements/hx-tabpanel/index.spec.js
* implement `<hx-tabpanel>` component tests
* add FAILING tests to replicate HelixUI Issue #516 bugs
* **Once the dynamic tab bug patch is implemented, we will include these tests with our test run.**
Jira: SURF-2029
=> test(hx-tabpanel): implement component tests

src/elements/hx-tabset/index.spec.js
* implement `<hx-tabset>` component tests
* add FAILING tests to replicate HelixUI Issue #516 bugs
* **Once the dynamic tab bug patch is implemented, we will include these tests with our test run.**
Jira: SURF-2030
=> test(hx-tabset): implement component tests

src/elements/hx-tab/index.spec.js, src/elements/hx-tabcontent/index.spec.js, src/elements/hx-tablist/index.spec.js, src/elements/hx-tabpanel/index.spec.js, src/elements/hx-tabset/index.js, src/elements/hx-tabset/index.spec.js
* Fixes #516
* fix for dynamic tabs
* fix for no id on tabset on render
* fix for no tabpanel on render
* fix for no tab on render
* fix for no tab or tabpanel on render
* test an odd number of tabs and tabpanel
* test an odd number of tabpanels and tab
Jira: SURF-1756
=> fix(tabset): dynamic tabs bug fixes Issue #516

src/elements/hx-tabset/index.spec.js
* Feature Request from Issue #516 
* Ability to add a dynamic tab with ID on render (without needing to manually run `update()`.
Jira: SURF-2070
=> test(hx-tabset): add dynamic tab with id on render

src/elements/hx-tab/index.js, src/elements/hx-tabpanel/index.js, src/elements/hx-tabset/index.js, src/elements/hx-tabset/index.spec.js
Implement better support for dynamic tabs. (Requested Issue #516 and Issue #758)
Jira: SURF-2071
=> feat(tabset): implement better support for dynamic tabs

docs/components/beacon/beacon-demo.js, docs/components/beacon/index.html, src/elements/hx-beacon/_shadow.scss, src/scss/components/beacon/index.scss
To override the default Beacon styles.
Jira: SURF-2067
=> feat(beacon): implement override option for default styles

docs/_data/nav.json5, docs/components/secnav/index.html, docs/components/secnav/secnav-demo.js, docs/components/secnav/test.html, docs/docs.js, src/scss/components/_index.scss, src/scss/components/secnav/_config.scss, src/scss/components/secnav/index.scss, src/scss/components/secnav/mixins/_secNavControl.scss
Implement Sec Nav (Secondary Navigation).
Jira: SURF1766
=> feat(secnav): implement secondary navigation component

docs/components/topnav/test.html, src/scss/components/topnav/index.scss
Design Review for Top Navigation
Jira: SURF-2091
=> feat(topnav): design feedback for top navigation component

docs/_data/nav.json5, docs/components/typography/_index.scss, docs/components/typography/index.html, docs/images/helix-logo.svg, karma.sauce.config.js, src/less/components.less, src/less/vars.less, src/scss/_config.scss, src/scss/_vars-legacy.scss, src/scss/base/_typography.scss, src/scss/components/_config.scss, src/scss/components/table/_index.scss, src/scss/components/typography/_index.scss
Update styles - typography and colors.
Jira: SURF-2138
=> feat(styles): update typography and colors

src/scss/components/accordion/_stepper.scss
Implement and Document variables and attributes
Jira: SURF 2094
=> docs(accordion): implement and document vars and attrs

src/scss/components/drawer/_index.scss
`hx-drawer` : Implement and document attributes and variables
Jira: SURF 2104
=> docs(drawer): implement and document attrs and vars

src/scss/_vars.scss
Update color palette.
Jira: SURF-2146
=> feat(colors): update color palette

src/scss/components/radio/_index.scss, src/scss/components/radio/mixins/_hxRadioControl.scss, src/scss/components/radio/mixins/_hxRadioFacade.scss
* `Radio` component - new color palette specs
Jira: SURF-2148
=> feat(radio): new color palette specs

src/scss/components/form/mixins/_fieldName.scss, src/scss/components/form/mixins/_helpText.scss, src/scss/components/form/mixins/_textControl.scss, src/scss/components/text-input/_index.scss
`<hx-textinput>` implementing color palette 2.0 styles
Jira: SURF2158
=> refactor(textinput): update component specs

docs/components/topnav/index.html, docs/components/topnav/test.html, docs/components/topnav/topnav-demo.js, src/scss/components/topnav/index.scss
`<hx-topnav>` implementing color palette 2.0 styles
Jira: SURF 2142
=> refactor(topnav): update top navigation component specs

docs/components/secnav/index.html, docs/components/secnav/secnav-demo.js, docs/components/secnav/test.html, src/scss/components/secnav/index.scss
`<hx-secnav>` :  implementing color palette 2.0 styles
Jira: SURF2143
=> refactor(secnav): update secondary navigation component specs

docs/components/secnav/secnav-demo.js
`<hx-secnav>` : fix secnav-demo.js warnings
Jira: SURF2165
=> style(secnav): fix warnings

src/scss/components/button/mixins/_hxButton.scss, src/scss/components/pill/_index.scss, src/scss/components/popover/_index.scss
`<hx-button>` : Implementing color palette styles
Jira: SURF-2152
=> feat(button): new component specs

docs/components/icon/index.html, src/scss/components/choice-tile/_index.scss, src/scss/components/choice-tile/mixins/_hxChoiceTile.scss
`<hx-choicetile>`:  implementing color palette 2.0 styles
Jira: SURF2153
=> feat(choice tile): new component specs

src/scss/components/checkbox/_index.scss, src/scss/components/checkbox/mixins/_hxCheckboxControl.scss, src/scss/components/checkbox/mixins/_hxCheckboxFacade.scss
`hx-checkbox` : implement and document variables and attributes
Jira: SURF-2102
=> docs(checkbox): implement and document vars and attrs

src/scss/components/choice-tile/_index.scss, src/scss/components/choice-tile/mixins/_hxChoiceTile.scss
`hx-choicetile` :  implement and document variables and attributes
Jira: SURF 2103
=> docs(choice-tile): implement and document vars and attrs

src/scss/components/dropdown-select/mixins/SelectControl.scss, src/scss/components/dropdown-select/mixins/SelectFacade.scss
`hx-dropdownSelect` : Implement and document attributes and variables
Jira: SURF 2105
=> docs(dropdown): implement and document attrs and vars

src/scss/components/menu/_index.scss
`<hx-menu>` : Implement and Document variables and attributes
Jira: SURF-2113
=> docs(hx-menu): implement and document vars and attrs

src/scss/_vars.scss, src/scss/components/button/mixins/_hxButton.scss, src/scss/components/button/mixins/_hxButtonBar.scss, src/scss/components/checkbox/_index.scss, src/scss/components/popover/_index.scss, src/scss/components/radio/_index.scss
* remove button 2px `border-radius`
* update checkbox specs
* update radio specs
* update popover specs
Jira:
* SURF-2171
* SURF-2173
* SURF-2174
=> feat(various): update component specs

src/scss/components/radio/_index.scss, src/scss/components/radio/mixins/_hxRadioControl.scss, src/scss/components/radio/mixins/_hxRadioFacade.scss
`<hx-radio>` : Implement and document attribute and variables
Jira: SURF 2123
=> docs(hx-radio): implement and document vars and attrs

src/scss/components/popover/_index.scss
`<hx-popover>` : implement and document attributes and variables
Jira: SURF-2122
=> docs(popover): implement and document attrs and vars

src/scss/components/file/_hx-drop-fence.scss, src/scss/components/file/_hx-drop-zone.scss, src/scss/components/file/_hx-file-control.scss, src/scss/components/file/_hx-file-tile.scss
`<hx-file>` : implement and document attributes and variables
Jira: SURF-2107
=> docs(file): implement and document attrs and vars

docs/components/choice-tile/choice-tile-demo.js, src/scss/components/choice-tile/_index.scss, src/scss/components/choice-tile/mixins/_hxChoiceTile.scss
`<hx-choice-tile>`: Added the new slim option choice tile
Jira: SURF-2154
=> feat(choice-tile): implement new slim option

docs/components/checkbox/_spec.scss, src/scss/_vars.scss, src/scss/components/checkbox/_index.scss, src/scss/components/checkbox/mixins/_hxCheckboxControl.scss, src/scss/components/checkbox/mixins/_hxCheckboxFacade.scss
Update Checkbox specs.
Jira: SURF-2182
=> feat(checkbox): update component specs

src/scss/components/breadcrumb/index.scss
`<breadcrumb>` :  implement design tokens
Jira: SURF-2200
=> refactor(breadcrumb): implement design tokens specs

src/scss/components/radio/_index.scss, src/scss/components/radio/mixins/_hxRadioControl.scss, src/scss/components/radio/mixins/_hxRadioFacade.scss
`<hx-radio>` : Added design tokens
Jira: SURF2204
=> refactor(radio): implement design tokens spec

src/scss/components/button/mixins/_hxButton.scss
Button Component - Implement design tokens specification.
Jira: SURF-2199
=> refactor(button): implement design tokens spec

src/elements/hx-tooltip/index.spec.js
* Fix flaky GH Action for `<hx-tooltip>` `$onConnect` test
Jira: SURF-2122
=> test(tooltip): fix flaky GH action - $onConnect

docs/_layout.scss
* Tweak docs `header` for new color palette specs.
=> chore(docs): tweak docs `header`
